apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-aktivitetslogg-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/internal/ishealthy"
  readiness:
    path: "/api/internal/ishealthy"
  startup:
    path: "/api/internal/ishealthy"
    initialDelay: 1
    periodSeconds: 3
    failureThreshold: 10
  replicas:
    min: 2
    max: 2
    disableAutoScaling: true
  prometheus:
    enabled: false
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - {{ingress}}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: nav.no
      claims:
        groups:
          - id: 4edb2ce5-4f0e-4f6f-9b82-b8e75e9dd09e # teamdagpenger
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-aktivitetslogg
