apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-aktivitetslogg-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{image}}"
  port: 3000
  liveness:
    path: "/api/internal/ishealthy"
  readiness:
    path: "/api/internal/ishealthy"
  startup:
    path: "/api/internal/ishealthy"
    initialDelay: 1
    periodSeconds: 3
    failureThreshold: 10
  replicas:
    min: 2
    max: 2
    disableAutoScaling: true
  prometheus:
    enabled: false
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  {{ ingresses }}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: trygdeetaten.no
      claims:
        groups:
          - id: "3e28466f-c53d-46da-8b44-a4abc2ad4593" # 0000-GA-Dagpenger-Saksbehandler
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-aktivitetslogg
