name: E2E

on:
  push:

jobs:
  e2e:
    name: playwright
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: "read"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: "24.x"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache node_modules
        uses: actions/cache@v6
        id: node_modules
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: pnpm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Generate API types
        run: pnpm run generate-api-types

      - name: Cache Playwright browsers
        uses: actions/cache@v6
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps chromium

      - name: Install Playwright OS deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps chromium

      - name: Run Playwright tests
        run: pnpm run test:e2e

      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
